# Generated by Django 4.0.2 on 2025-09-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
