# Generated by Django 4.0.2 on 2025-09-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_cinemahall_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat',
            new_name='seats',
        ),
    ]
