# Generated by Django 4.0.2 on 2025-09-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_seat_ticket_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seats',
            new_name='seat',
        ),
    ]
